### ISSUE TITLE
IndexError when running run.py

### ISSUE THREAD

**Issue by nickpieper** [gu4xin1m/TenableTagAgentGroups#1]
Error:
IndexError: list index out of range

Full Error:
[*]Geting tenable asset data...
Waiting 5 seconds for Tenable to generate the report
Done
[*] Downloading the report...
Traceback (most recent call last):
  File "/home/ubuntu/TenableTagAgentGroups/run.py", line 19, in <module>
    tag = tenableApi.getTagId(agentGroupName)
  File "/home/ubuntu/TenableTagAgentGroups/tenableApi.py", line 101, in getTagId
    responseList['uuid'] = responseJson["values"][0]['uuid']
IndexError: list index out of range

Recreation:
I commented out the final line so I can test the script before deploying it to our Tenable.IO instance.

**Comment by gu4xin1m** [comment]
Is there is any agent group name that don't has a tag  an equivalent tag category ? The script will try to find tag category for every agent group, this might be the reason. Can you confirm that ?

**Comment by gu4xin1m** [comment]
@nickpieper , I added a fix for the issue. Let me know if it's working now.
